<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/Data_loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import pandas as pd
import numpy as np

In [4]:
# change directories to relative paths using Images1, Images2, Images3 folders

def change_dir_cols(df):  
    df_dir = df["dir"]

    dir_1 = "/content/Generated_Images_7-2-24/"
    dir_2 = "/content/Generated Images/"
    dir_3 = "/content/05-09-2024_all_images/"

    new_dir_1 = "content/Images1/"
    new_dir_2 = "content/Images2/"
    new_dir_3 = "content/Images3/"

    for i in range(len(df_dir)):
        if df_dir[i].startswith(dir_1):
            df_dir[i] = df_dir[i].replace(dir_1, new_dir_1)
        elif df_dir[i].startswith(dir_2):
            df_dir[i] = df_dir[i].replace(dir_2, new_dir_2)
        elif df_dir[i].startswith(dir_3):
            df_dir[i] = df_dir[i].replace(dir_3,new_dir_3)
        else:
            print("unrecognized directory:", df_dir[i])
    return df

In [7]:
with open("data/manual_classification_cl6.pkl", 'rb') as f:
    df = pickle.load(f) # deserialize using load()

df.head()

,class,noise,path,seed,dir
0,3,4,noise 4 20604.0.png,20604.0,/content/Generated_Images_7-2-24/
1,3,6,noise 6 20289.0.png,20289.0,/content/Generated_Images_7-2-24/
2,4,23782.0,noise 6 23782.0.png,23782.0,/content/Generated Images/
3,2,2,7761.png,7761,/content/05-09-2024_all_images/
4,1,2,8366.png,8366,/content/05-09-2024_all_images/

In [8]:
df = change_dir_cols(df)

df.head()

  class    noise                 path     seed               dir
0     3        4  noise 4 20604.0.png  20604.0  content/Images1/
1     3        6  noise 6 20289.0.png  20289.0  content/Images1/
2     4  23782.0  noise 6 23782.0.png  23782.0  content/Images2/
3     2        2             7761.png     7761  content/Images3/
4     1        2             8366.png     8366  content/Images3/

In [9]:
file_name = "data/manual_classification_cl6_updated_image_dir.pkl"

with open(file_name, 'wb') as f:
        pickle.dump(df, f)